spring:
  datasource:
    url: jdbc:mysql://localhost:3306/redis1
    username: fconsiglio98
    password: inserirePassword
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

redis:
  database: redis-1
  password: inserirePassword
  host: inserireHost
  port: 16143

